server:
  port: 800

github:
  client:
    id: 146dfe1b54d1a3dce100
    secret: c302b2b6d9504e91972d9c0dd3e28d26292fdfe9
  redirect:
    uri: http://localhost:800/callback

spring:
  datasource:
    url: jdbc:h2:E:\h2datasource\community
    username: community
    password: community
    driver-class-name: org.h2.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.moc.community.mapper
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
    com.moc.community.mapper: debug

  file: C:/Users/Administrator/Desktop/logs/community.log
  file.max-size: 200MB    # 日志文件最大10MB
  file.max-history: 30    # 仅保留近三天的日志

